/* soapH.h
   Generated by gSOAP 2.8.18 from fm.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE___ns1__queryFm
#define SOAP_TYPE___ns1__queryFm (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__queryFm(struct soap*, struct __ns1__queryFm *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__queryFm(struct soap*, const struct __ns1__queryFm *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__queryFm(struct soap*, const char*, int, const struct __ns1__queryFm *, const char*);
SOAP_FMAC3 struct __ns1__queryFm * SOAP_FMAC4 soap_in___ns1__queryFm(struct soap*, const char*, struct __ns1__queryFm *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__queryFm(struct soap*, const struct __ns1__queryFm *, const char*, const char*);

#ifndef soap_write___ns1__queryFm
#define soap_write___ns1__queryFm(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__queryFm(soap, data),0) || soap_put___ns1__queryFm(soap, data, "-ns1:queryFm", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__queryFm * SOAP_FMAC4 soap_get___ns1__queryFm(struct soap*, struct __ns1__queryFm *, const char*, const char*);

#ifndef soap_read___ns1__queryFm
#define soap_read___ns1__queryFm(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__queryFm(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_ns3__OrganizationInfo
#define SOAP_TYPE_ns3__OrganizationInfo (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__OrganizationInfo(struct soap*, struct ns3__OrganizationInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__OrganizationInfo(struct soap*, const struct ns3__OrganizationInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__OrganizationInfo(struct soap*, const char*, int, const struct ns3__OrganizationInfo *, const char*);
SOAP_FMAC3 struct ns3__OrganizationInfo * SOAP_FMAC4 soap_in_ns3__OrganizationInfo(struct soap*, const char*, struct ns3__OrganizationInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__OrganizationInfo(struct soap*, const struct ns3__OrganizationInfo *, const char*, const char*);

#ifndef soap_write_ns3__OrganizationInfo
#define soap_write_ns3__OrganizationInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns3__OrganizationInfo(soap, data),0) || soap_put_ns3__OrganizationInfo(soap, data, "ns3:OrganizationInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns3__OrganizationInfo * SOAP_FMAC4 soap_get_ns3__OrganizationInfo(struct soap*, struct ns3__OrganizationInfo *, const char*, const char*);

#ifndef soap_read_ns3__OrganizationInfo
#define soap_read_ns3__OrganizationInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__OrganizationInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns3__AuthInfo
#define SOAP_TYPE_ns3__AuthInfo (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns3__AuthInfo(struct soap*, struct ns3__AuthInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns3__AuthInfo(struct soap*, const struct ns3__AuthInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__AuthInfo(struct soap*, const char*, int, const struct ns3__AuthInfo *, const char*);
SOAP_FMAC3 struct ns3__AuthInfo * SOAP_FMAC4 soap_in_ns3__AuthInfo(struct soap*, const char*, struct ns3__AuthInfo *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns3__AuthInfo(struct soap*, const struct ns3__AuthInfo *, const char*, const char*);

#ifndef soap_write_ns3__AuthInfo
#define soap_write_ns3__AuthInfo(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns3__AuthInfo(soap, data),0) || soap_put_ns3__AuthInfo(soap, data, "ns3:AuthInfo", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns3__AuthInfo * SOAP_FMAC4 soap_get_ns3__AuthInfo(struct soap*, struct ns3__AuthInfo *, const char*, const char*);

#ifndef soap_read_ns3__AuthInfo
#define soap_read_ns3__AuthInfo(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__AuthInfo(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns2__queryFmResponse
#define SOAP_TYPE_ns2__queryFmResponse (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryFmResponse(struct soap*, struct ns2__queryFmResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryFmResponse(struct soap*, const struct ns2__queryFmResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryFmResponse(struct soap*, const char*, int, const struct ns2__queryFmResponse *, const char*);
SOAP_FMAC3 struct ns2__queryFmResponse * SOAP_FMAC4 soap_in_ns2__queryFmResponse(struct soap*, const char*, struct ns2__queryFmResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryFmResponse(struct soap*, const struct ns2__queryFmResponse *, const char*, const char*);

#ifndef soap_write_ns2__queryFmResponse
#define soap_write_ns2__queryFmResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns2__queryFmResponse(soap, data),0) || soap_put_ns2__queryFmResponse(soap, data, "ns2:queryFmResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__queryFmResponse * SOAP_FMAC4 soap_get_ns2__queryFmResponse(struct soap*, struct ns2__queryFmResponse *, const char*, const char*);

#ifndef soap_read_ns2__queryFmResponse
#define soap_read_ns2__queryFmResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryFmResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns2__queryFm
#define SOAP_TYPE_ns2__queryFm (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__queryFm(struct soap*, struct ns2__queryFm *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__queryFm(struct soap*, const struct ns2__queryFm *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__queryFm(struct soap*, const char*, int, const struct ns2__queryFm *, const char*);
SOAP_FMAC3 struct ns2__queryFm * SOAP_FMAC4 soap_in_ns2__queryFm(struct soap*, const char*, struct ns2__queryFm *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__queryFm(struct soap*, const struct ns2__queryFm *, const char*, const char*);

#ifndef soap_write_ns2__queryFm
#define soap_write_ns2__queryFm(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns2__queryFm(soap, data),0) || soap_put_ns2__queryFm(soap, data, "ns2:queryFm", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__queryFm * SOAP_FMAC4 soap_get_ns2__queryFm(struct soap*, struct ns2__queryFm *, const char*, const char*);

#ifndef soap_read_ns2__queryFm
#define soap_read_ns2__queryFm(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__queryFm(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_ns2__ServiceException
#define SOAP_TYPE_ns2__ServiceException (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__ServiceException(struct soap*, struct ns2__ServiceException *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__ServiceException(struct soap*, const struct ns2__ServiceException *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__ServiceException(struct soap*, const char*, int, const struct ns2__ServiceException *, const char*);
SOAP_FMAC3 struct ns2__ServiceException * SOAP_FMAC4 soap_in_ns2__ServiceException(struct soap*, const char*, struct ns2__ServiceException *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__ServiceException(struct soap*, const struct ns2__ServiceException *, const char*, const char*);

#ifndef soap_write_ns2__ServiceException
#define soap_write_ns2__ServiceException(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_ns2__ServiceException(soap, data),0) || soap_put_ns2__ServiceException(soap, data, "ns2:ServiceException", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__ServiceException * SOAP_FMAC4 soap_get_ns2__ServiceException(struct soap*, struct ns2__ServiceException *, const char*, const char*);

#ifndef soap_read_ns2__ServiceException
#define soap_read_ns2__ServiceException(soap, data) ( soap_begin_recv(soap) || !soap_get_ns2__ServiceException(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTons2__queryFmResponse
#define SOAP_TYPE_PointerTons2__queryFmResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryFmResponse(struct soap*, struct ns2__queryFmResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryFmResponse(struct soap*, const char *, int, struct ns2__queryFmResponse *const*, const char *);
SOAP_FMAC3 struct ns2__queryFmResponse ** SOAP_FMAC4 soap_in_PointerTons2__queryFmResponse(struct soap*, const char*, struct ns2__queryFmResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryFmResponse(struct soap*, struct ns2__queryFmResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryFmResponse
#define soap_write_PointerTons2__queryFmResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons2__queryFmResponse(soap, data),0) || soap_put_PointerTons2__queryFmResponse(soap, data, "ns2:queryFmResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__queryFmResponse ** SOAP_FMAC4 soap_get_PointerTons2__queryFmResponse(struct soap*, struct ns2__queryFmResponse **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryFmResponse
#define soap_read_PointerTons2__queryFmResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryFmResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__queryFm
#define SOAP_TYPE_PointerTons2__queryFm (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__queryFm(struct soap*, struct ns2__queryFm *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__queryFm(struct soap*, const char *, int, struct ns2__queryFm *const*, const char *);
SOAP_FMAC3 struct ns2__queryFm ** SOAP_FMAC4 soap_in_PointerTons2__queryFm(struct soap*, const char*, struct ns2__queryFm **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__queryFm(struct soap*, struct ns2__queryFm *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__queryFm
#define soap_write_PointerTons2__queryFm(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons2__queryFm(soap, data),0) || soap_put_PointerTons2__queryFm(soap, data, "ns2:queryFm", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__queryFm ** SOAP_FMAC4 soap_get_PointerTons2__queryFm(struct soap*, struct ns2__queryFm **, const char*, const char*);

#ifndef soap_read_PointerTons2__queryFm
#define soap_read_PointerTons2__queryFm(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__queryFm(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons2__ServiceException
#define SOAP_TYPE_PointerTons2__ServiceException (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__ServiceException(struct soap*, struct ns2__ServiceException *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__ServiceException(struct soap*, const char *, int, struct ns2__ServiceException *const*, const char *);
SOAP_FMAC3 struct ns2__ServiceException ** SOAP_FMAC4 soap_in_PointerTons2__ServiceException(struct soap*, const char*, struct ns2__ServiceException **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__ServiceException(struct soap*, struct ns2__ServiceException *const*, const char*, const char*);

#ifndef soap_write_PointerTons2__ServiceException
#define soap_write_PointerTons2__ServiceException(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons2__ServiceException(soap, data),0) || soap_put_PointerTons2__ServiceException(soap, data, "ns2:ServiceException", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct ns2__ServiceException ** SOAP_FMAC4 soap_get_PointerTons2__ServiceException(struct soap*, struct ns2__ServiceException **, const char*, const char*);

#ifndef soap_read_PointerTons2__ServiceException
#define soap_read_PointerTons2__ServiceException(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons2__ServiceException(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
