/* soapStub.h
   Generated by gSOAP 2.8.18 from fm.h

Copyright(C) 2000-2014, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_ns2	"http://www.lab503.cn/schema/dataengine/v1/local"
#define SOAP_NAMESPACE_OF_ns3	"http://www.lab503.cn/schema/dataengine/v1/types"
#include "stdsoap2.h"
#if GSOAP_VERSION != 20818
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif

#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_ns2__ServiceException
#define SOAP_TYPE_ns2__ServiceException (7)
/* ns2:ServiceException */
struct ns2__ServiceException
{
	char *messageId;	/* required element of type xsd:string */
	char *text;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__queryFm
#define SOAP_TYPE_ns2__queryFm (8)
/* ns2:queryFm */
struct ns2__queryFm
{
	char *userId;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__queryFmResponse
#define SOAP_TYPE_ns2__queryFmResponse (9)
/* ns2:queryFmResponse */
struct ns2__queryFmResponse
{
	char *fmId;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__AuthInfo
#define SOAP_TYPE_ns3__AuthInfo (10)
/* ns3:AuthInfo */
struct ns3__AuthInfo
{
	char *clientId;	/* required element of type xsd:string */
	char *timeStamp;	/* required element of type xsd:string */
	char *passwd;	/* required element of type xsd:string */
	char *opPerson;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns3__OrganizationInfo
#define SOAP_TYPE_ns3__OrganizationInfo (11)
/* ns3:OrganizationInfo */
struct ns3__OrganizationInfo
{
	char *fmId;	/* required element of type xsd:string */
	int wbRid;	/* required element of type xsd:int */
	char *fmName;	/* required element of type xsd:string */
	char *url;	/* required element of type xsd:string */
	char *intro;	/* required element of type xsd:string */
	char *logoAddr;	/* required element of type xsd:string */
	char *weiboAddr;	/* required element of type xsd:string */
	int province;	/* required element of type xsd:int */
	char *hdvAddr;	/* required element of type xsd:string */
	char *microAddr;	/* required element of type xsd:string */
	char *updateTime;	/* required element of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (12)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	struct ns2__ServiceException *ns2__ServiceException;	/* optional element of type ns2:ServiceException */
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#endif

#ifndef SOAP_TYPE___ns1__queryFm
#define SOAP_TYPE___ns1__queryFm (19)
/* Operation wrapper: */
struct __ns1__queryFm
{
	struct ns2__queryFm *ns2__queryFm;	/* optional element of type ns2:queryFm */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (20)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (21)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (23)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __ns1__queryFm(struct soap*, struct ns2__queryFm *ns2__queryFm, struct ns2__queryFmResponse *ns2__queryFmResponse);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___ns1__queryFm(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__queryFm(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct ns2__queryFm *ns2__queryFm, struct ns2__queryFmResponse *ns2__queryFmResponse);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
