/* soapClient.cpp
   Generated by gSOAP 2.8.14 from ssl.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.14 2013-03-31 11:10:41 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__upload_message(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *Device_ID, int returntype, struct ns__MsgList *state, char *authstr, struct ns__ResultList *result)
{	struct ns__upload_message soap_tmp_ns__upload_message;
	struct ns__upload_messageResponse *soap_tmp_ns__upload_messageResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://127.0.0.1:8000";
	soap->encodingStyle = "";
	soap_tmp_ns__upload_message.Device_ID = Device_ID;
	soap_tmp_ns__upload_message.returntype = returntype;
	soap_tmp_ns__upload_message.state = state;
	soap_tmp_ns__upload_message.authstr = authstr;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__upload_message(soap, &soap_tmp_ns__upload_message);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__upload_message(soap, &soap_tmp_ns__upload_message, "ns:upload-message", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__upload_message(soap, &soap_tmp_ns__upload_message, "ns:upload-message", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!result)
		return soap_closesock(soap);
	soap_default_ns__ResultList(soap, result);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__upload_messageResponse = soap_get_ns__upload_messageResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (result && soap_tmp_ns__upload_messageResponse->result)
		*result = *soap_tmp_ns__upload_messageResponse->result;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__PutData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct x__DataSet *x__data, struct x__Keys *x__keys, char *device_id, char *authstr, int *response)
{	struct ns__PutData soap_tmp_ns__PutData;
	struct ns__PutDataResponse *soap_tmp_ns__PutDataResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "https://127.0.0.1:8000";
	soap->encodingStyle = "";
	soap_tmp_ns__PutData.x__data = x__data;
	soap_tmp_ns__PutData.x__keys = x__keys;
	soap_tmp_ns__PutData.device_id = device_id;
	soap_tmp_ns__PutData.authstr = authstr;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__PutData(soap, &soap_tmp_ns__PutData);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__PutData(soap, &soap_tmp_ns__PutData, "ns:PutData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__PutData(soap, &soap_tmp_ns__PutData, "ns:PutData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!response)
		return soap_closesock(soap);
	soap_default_int(soap, response);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	if (soap_recv_fault(soap, 1))
		return soap->error;
	soap_tmp_ns__PutDataResponse = soap_get_ns__PutDataResponse(soap, NULL, "", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	if (response && soap_tmp_ns__PutDataResponse->response)
		*response = *soap_tmp_ns__PutDataResponse->response;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__GetData(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct x__Keys *x__keys, char *device_id, char *authstr, struct ns__GetDataResponse *_param_1)
{	struct ns__GetData soap_tmp_ns__GetData;
	printf("soap_call_ns_GetData start\n");
	if (soap_endpoint == NULL)
	{
		printf("soap_endpoint == NULL\n");
		soap_endpoint = "https://127.0.0.1:8000";
	}
	soap->encodingStyle = "";
	soap_tmp_ns__GetData.x__keys = x__keys;
	soap_tmp_ns__GetData.device_id = device_id;
	soap_tmp_ns__GetData.authstr = authstr;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize_ns__GetData(soap, &soap_tmp_ns__GetData);
	if (soap_begin_count(soap))
	{
		printf("soap_begin_count(soap)\n");
		return soap->error;
	}
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__GetData(soap, &soap_tmp_ns__GetData, "ns:GetData", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
		{
			printf("soap->mode & SOAP_IO_LENGTH\n");
			 return soap->error;
		}
	}
	if (soap_end_count(soap))
	{
		printf("soap_end_count(soap)\n");
		return soap->error;
	}
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__GetData(soap, &soap_tmp_ns__GetData, "ns:GetData", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
	{
		printf("soap_connect(soap, soap_endpoint, soap_action)|| soap_envelope_begin_out(soap)|| soap_putheader(soap)|| soap_body_begin_out(soap)|| soap_put_ns__GetData(soap, &soap_tmp_ns__GetData, ns:GetData, NULL)|| soap_body_end_out(soap)|| soap_envelope_end_out(soap)|| soap_end_send(soap)\n");
		return soap_closesock(soap);
	}
	if (!_param_1)
	{  
		printf("!_param_1\n");
		return soap_closesock(soap);
	}
	soap_default_ns__GetDataResponse(soap, _param_1);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
	{
		printf("soap_begin_recv(soap)\
										   || soap_envelope_begin_in(soap)\
											    || soap_recv_header(soap)\
													   || soap_body_begin_in(soap)\n");
		return soap_closesock(soap);
	}
	if (soap_recv_fault(soap, 1))
	{
		printf("soap_recv_fault(soap, 1)\n");
		return soap->error;
	}
	soap_get_ns__GetDataResponse(soap, _param_1, "", "");
	if (soap->error)
	{
		printf("soap->error\n");
		return soap_recv_fault(soap, 0);
	}
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
	{
		printf("soap_body_end_in(soap)\
										   || soap_envelope_end_in(soap)\
											    || soap_end_recv(soap)\n");
		return soap_closesock(soap);
	}
	printf("soap_call_ns_GetData end\n");
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
